### ISSUE TITLE
ArUserSetPassword does not reset when new user created

### ISSUE THREAD

**Issue by ahurm** [stephan1827/mappView-User#21] opened 2020-08-31 10:41 UTC
If user is created via Create User -button, ArUserSetPassword function does not reset. Execute-parameter stays TRUE. This causes the issue that if more than one new user is created the first one will have set password but the other ones will be created without password.

I fixed the issue by resetting function when it is done but not busy.
```
...
ChangePassword:
  ArUserSetPassword_0(Execute := TRUE, UserName := tmpUser, Password := ArUser.PAR.Password);
  IF ArUserSetPassword_0.Done AND NOT ArUserSetPassword_0.Busy THEN
    ArUserSetPassword_0(Execute := FALSE); // Resets function
...
```

**Comment by stephan1827** [comment] 2020-08-31 11:24
Thanks for the report. I disable the function block when you change the password but this also has to be done when you create a new user. The issue is fixed in commit ee6bb14.

**Closed as completed by stephan1827** 2020-08-31 11:24 UTC
